name: Assign Issue

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: actions-ecosystem/action-assign@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: "KellamA" # Replace "Kellam" with the GitHub username
