name: Auto Assign Issue

on:
  issues:
    types:
      - opened

jobs:
  assign-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Issue
        uses: actions/assign-issue@v2.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: 'KellamA' # Replace with the GitHub username of the assignee
