name: Auto Assign Issue

on:
  issues:
    types:
      - opened

permissions:
  issues: write  # Ensures the workflow can modify issues

jobs:
  assign-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Issue
        uses: ridedott/assign-issue@v2.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: 'KellamA' # Replace with the GitHub username
